export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAIL = "GET_PROJECTS_FAIL";
export const SET_PROJECT_SUCCESS = "SET_PROJECT_SUCCESS";
export const SET_PROJECT_FAIL = "SET_PROJECT_FAIL";
export const NEW_PROJECT_SUCCESS = "NEW_PROJECT_SUCCESS";
export const NEW_PORJECT_FAIL = "NEW_PORJECT_FAIL";
export const EDIT_PROJECT_SUCCESS = "EDIT_PROJECT_SUCCESS";
export const EDIT_PROJECT_FAIL = "EDIT_PROJECT_FAIL";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";
export const CLEAR_PROJECTS = "CLEAR_PROJECTS";
export const CLEAR_CURRENT_PROJECT = "CLEAR_CURRENT_PROJECT";
export const CLEAR_PROJECTS_ERRORS = "CLEAR_PROJECTS_ERRORS";

export const GET_BUGS_SUCCESS = "GET_BUGS_SUCCESS";
export const GET_BUGS_FAIL = "GET_BUGS_FAIL";
export const UPDATE_BUG_SUCCESS = "UPDATE_BUG_SUCCESS";
export const UPDATE_BUG_FAIL = "UPDATE_BUG_FAIL";
export const NEW_BUG_SUCCESS = "NEW_BUG_SUCCESS";
export const NEW_BUG_FAIL = "NEW_BUG_FAIL";
export const DELETE_BUG_SUCCESS = "DELETE_BUG_SUCCESS";
export const DELETE_BUG_FAIL = "DELETE_BUG_FAIL";
export const SORT_BUGS = "SORT_BUGS";
export const CLEAR_BUGS_ERRORS = "CLEAR_BUGS_ERRORS";
export const CLEAR_BUGS = "CLEAR_BUGS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const GET_ME_SUCCESS = "GET_ME_SUCCESS";
export const GET_ME_FAIL = "GET_ME_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const CLEAR_AUTH_ERRORS = "CLEAR_AUTH_ERRORS";

export const DARKMODE_ON = "DARKMODE_ON";
export const DARKMODE_OFF = "DARKMODE_OFF";
